### ISSUE TITLE
No rule to make target '/usr/local/lib/libz.so.1', needed by 'RGBDConverter'

### ISSUE THREAD

**Issue by leyuan-sun** [chaowang15/RGBDConverter#2]
Scanning dependencies of target RGBDConverter
[ 25%] Building CXX object CMakeFiles/RGBDConverter.dir/main.cpp.o
[ 50%] Building CXX object CMakeFiles/RGBDConverter.dir/RGBDConverter.cpp.o
make[2]: *** No rule to make target '/usr/local/lib/libz.so.1', needed by 'RGBDConverter'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 75%] Building CXX object CMakeFiles/RGBDConverter.dir/DataCompression.cpp.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/RGBDConverter.dir/all' failed
make[1]: *** [CMakeFiles/RGBDConverter.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by margaritaG** [comment]
@SUNLEYUAN It is failing at [this line](https://github.com/chaowang15/RGBDConverter/blob/master/RGBDConverter/CMakeLists.txt#L12) because on your system the zlib library cannot be found at the path which is hardcoded there.

One easy fix is to edit the line and set the correct path for your zlib library.
